// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package pbRole

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventOpt int32

const (
	EventOpt_setName EventOpt = 0
	EventOpt_addItem EventOpt = 1
)

var EventOpt_name = map[int32]string{
	0: "setName",
	1: "addItem",
}

var EventOpt_value = map[string]int32{
	"setName": 0,
	"addItem": 1,
}

func (x EventOpt) String() string {
	return proto.EnumName(EventOpt_name, int32(x))
}

func (EventOpt) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

type Events struct {
	TranId               int64          `protobuf:"varint,1,opt,name=tranId,proto3" json:"tranId,omitempty"`
	AggregateRoot        int64          `protobuf:"varint,2,opt,name=aggregateRoot,proto3" json:"aggregateRoot,omitempty"`
	AggregateVersion     int64          `protobuf:"varint,3,opt,name=aggregateVersion,proto3" json:"aggregateVersion,omitempty"`
	BornAt               int64          `protobuf:"varint,4,opt,name=bornAt,proto3" json:"bornAt,omitempty"`
	ExecAt               int64          `protobuf:"varint,5,opt,name=execAt,proto3" json:"execAt,omitempty"`
	Trans                *DomainEvent   `protobuf:"bytes,6,opt,name=trans,proto3" json:"trans,omitempty"`
	Repos                []*DomainEvent `protobuf:"bytes,7,rep,name=repos,proto3" json:"repos,omitempty"`
	Syncs                []*DomainEvent `protobuf:"bytes,8,rep,name=syncs,proto3" json:"syncs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (m *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(m, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetTranId() int64 {
	if m != nil {
		return m.TranId
	}
	return 0
}

func (m *Events) GetAggregateRoot() int64 {
	if m != nil {
		return m.AggregateRoot
	}
	return 0
}

func (m *Events) GetAggregateVersion() int64 {
	if m != nil {
		return m.AggregateVersion
	}
	return 0
}

func (m *Events) GetBornAt() int64 {
	if m != nil {
		return m.BornAt
	}
	return 0
}

func (m *Events) GetExecAt() int64 {
	if m != nil {
		return m.ExecAt
	}
	return 0
}

func (m *Events) GetTrans() *DomainEvent {
	if m != nil {
		return m.Trans
	}
	return nil
}

func (m *Events) GetRepos() []*DomainEvent {
	if m != nil {
		return m.Repos
	}
	return nil
}

func (m *Events) GetSyncs() []*DomainEvent {
	if m != nil {
		return m.Syncs
	}
	return nil
}

type DomainEvent struct {
	Opt                  EventOpt `protobuf:"varint,1,opt,name=opt,proto3,enum=pbRole.EventOpt" json:"opt,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainEvent) Reset()         { *m = DomainEvent{} }
func (m *DomainEvent) String() string { return proto.CompactTextString(m) }
func (*DomainEvent) ProtoMessage()    {}
func (*DomainEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *DomainEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainEvent.Unmarshal(m, b)
}
func (m *DomainEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainEvent.Marshal(b, m, deterministic)
}
func (m *DomainEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainEvent.Merge(m, src)
}
func (m *DomainEvent) XXX_Size() int {
	return xxx_messageInfo_DomainEvent.Size(m)
}
func (m *DomainEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DomainEvent proto.InternalMessageInfo

func (m *DomainEvent) GetOpt() EventOpt {
	if m != nil {
		return m.Opt
	}
	return EventOpt_setName
}

func (m *DomainEvent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type DomainEventSetName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainEventSetName) Reset()         { *m = DomainEventSetName{} }
func (m *DomainEventSetName) String() string { return proto.CompactTextString(m) }
func (*DomainEventSetName) ProtoMessage()    {}
func (*DomainEventSetName) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1, 0}
}

func (m *DomainEventSetName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainEventSetName.Unmarshal(m, b)
}
func (m *DomainEventSetName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainEventSetName.Marshal(b, m, deterministic)
}
func (m *DomainEventSetName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainEventSetName.Merge(m, src)
}
func (m *DomainEventSetName) XXX_Size() int {
	return xxx_messageInfo_DomainEventSetName.Size(m)
}
func (m *DomainEventSetName) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainEventSetName.DiscardUnknown(m)
}

var xxx_messageInfo_DomainEventSetName proto.InternalMessageInfo

func (m *DomainEventSetName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DomainEventAddItem struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Delta                int32    `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainEventAddItem) Reset()         { *m = DomainEventAddItem{} }
func (m *DomainEventAddItem) String() string { return proto.CompactTextString(m) }
func (*DomainEventAddItem) ProtoMessage()    {}
func (*DomainEventAddItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1, 1}
}

func (m *DomainEventAddItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainEventAddItem.Unmarshal(m, b)
}
func (m *DomainEventAddItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainEventAddItem.Marshal(b, m, deterministic)
}
func (m *DomainEventAddItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainEventAddItem.Merge(m, src)
}
func (m *DomainEventAddItem) XXX_Size() int {
	return xxx_messageInfo_DomainEventAddItem.Size(m)
}
func (m *DomainEventAddItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainEventAddItem.DiscardUnknown(m)
}

var xxx_messageInfo_DomainEventAddItem proto.InternalMessageInfo

func (m *DomainEventAddItem) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *DomainEventAddItem) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func init() {
	proto.RegisterEnum("pbRole.EventOpt", EventOpt_name, EventOpt_value)
	proto.RegisterType((*Events)(nil), "pbRole.Events")
	proto.RegisterType((*DomainEvent)(nil), "pbRole.DomainEvent")
	proto.RegisterType((*DomainEventSetName)(nil), "pbRole.DomainEvent.setName")
	proto.RegisterType((*DomainEventAddItem)(nil), "pbRole.DomainEvent.addItem")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xdd, 0x6e, 0x77, 0xb7, 0x9d, 0x45, 0x59, 0x46, 0x91, 0x50, 0x10, 0x4a, 0xe9, 0xa1,
	0xf6, 0x50, 0xb0, 0x3e, 0x41, 0x41, 0x0f, 0xbd, 0x28, 0xe4, 0xe0, 0x3d, 0xed, 0x0e, 0xa5, 0xd0,
	0x4d, 0x96, 0x64, 0x10, 0x7d, 0x18, 0x4f, 0xbe, 0xa8, 0x24, 0xe9, 0x16, 0x45, 0xf4, 0x96, 0xff,
	0x9f, 0x2f, 0xff, 0x0c, 0x33, 0x50, 0xd2, 0x2b, 0x69, 0x5e, 0xb4, 0xd6, 0xb0, 0xc1, 0xbc, 0xdd,
	0x48, 0x73, 0xa0, 0xc9, 0x67, 0x0f, 0xf2, 0x47, 0xef, 0x3b, 0xbc, 0x86, 0x9c, 0xad, 0xd2, 0xeb,
	0x5a, 0x24, 0xe3, 0x64, 0x96, 0xca, 0xa3, 0xc2, 0x29, 0x9c, 0xab, 0xdd, 0xce, 0xd2, 0x4e, 0x31,
	0x49, 0x63, 0x58, 0xf4, 0x42, 0xf9, 0xa7, 0x89, 0x73, 0xa8, 0x4e, 0xc6, 0x0b, 0x59, 0xb7, 0x37,
	0x5a, 0xa4, 0x01, 0xfc, 0xe5, 0xfb, 0x4e, 0x1b, 0x63, 0xf5, 0x8a, 0x45, 0x3f, 0x76, 0x8a, 0xca,
	0xfb, 0xf4, 0x46, 0xdb, 0x15, 0x8b, 0x2c, 0xfa, 0x51, 0xe1, 0x2d, 0x64, 0x7e, 0x16, 0x27, 0xf2,
	0x71, 0x32, 0x2b, 0x97, 0x97, 0x8b, 0x38, 0xfc, 0xe2, 0xc1, 0x34, 0x6a, 0xaf, 0xc3, 0xf8, 0x32,
	0x12, 0x1e, 0xb5, 0xd4, 0x1a, 0x27, 0x8a, 0x71, 0xfa, 0x27, 0x1a, 0x08, 0x8f, 0xba, 0x77, 0xbd,
	0x75, 0x62, 0xf0, 0x0f, 0x1a, 0x88, 0xc9, 0x47, 0x02, 0xe5, 0x37, 0x1b, 0x27, 0x90, 0x9a, 0x96,
	0xc3, 0x9e, 0x2e, 0x96, 0x55, 0xf7, 0x31, 0xd4, 0x9e, 0x5b, 0x96, 0xbe, 0x88, 0x02, 0x8a, 0xad,
	0xd1, 0x4c, 0x3a, 0x2e, 0x6c, 0x28, 0x3b, 0x39, 0xba, 0x81, 0xc2, 0x11, 0x3f, 0xa9, 0x86, 0x10,
	0xa1, 0xaf, 0x55, 0x43, 0x21, 0x69, 0x28, 0xc3, 0x7b, 0x74, 0x07, 0x85, 0xaa, 0xeb, 0x35, 0x53,
	0x83, 0x15, 0xa4, 0xbc, 0x8f, 0xf7, 0xc8, 0xa4, 0x7f, 0xe2, 0x15, 0x64, 0x35, 0x1d, 0x58, 0x85,
	0xcc, 0x4c, 0x46, 0x31, 0x9f, 0xc2, 0xa0, 0x6b, 0x8e, 0xe5, 0x29, 0xbd, 0x3a, 0xf3, 0xe2, 0x98,
	0x55, 0x25, 0x9b, 0x3c, 0x9c, 0xfe, 0xfe, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x83, 0xe4, 0x28, 0x57,
	0x09, 0x02, 0x00, 0x00,
}
