// Code generated by protoc-gen-go. DO NOT EDIT.
// source: module.proto

package pbRole

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ModOpt int32

const (
	ModOpt_info  ModOpt = 0
	ModOpt_items ModOpt = 1
)

var ModOpt_name = map[int32]string{
	0: "info",
	1: "items",
}

var ModOpt_value = map[string]int32{
	"info":  0,
	"items": 1,
}

func (x ModOpt) String() string {
	return proto.EnumName(ModOpt_name, int32(x))
}

func (ModOpt) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{0}
}

type Po struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Po) Reset()         { *m = Po{} }
func (m *Po) String() string { return proto.CompactTextString(m) }
func (*Po) ProtoMessage()    {}
func (*Po) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{0}
}

func (m *Po) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Po.Unmarshal(m, b)
}
func (m *Po) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Po.Marshal(b, m, deterministic)
}
func (m *Po) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Po.Merge(m, src)
}
func (m *Po) XXX_Size() int {
	return xxx_messageInfo_Po.Size(m)
}
func (m *Po) XXX_DiscardUnknown() {
	xxx_messageInfo_Po.DiscardUnknown(m)
}

var xxx_messageInfo_Po proto.InternalMessageInfo

type PoInfo struct {
	Uid                  int64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hash                 map[int64]*EntityItem `protobuf:"bytes,3,rep,name=hash,proto3" json:"hash,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PoInfo) Reset()         { *m = PoInfo{} }
func (m *PoInfo) String() string { return proto.CompactTextString(m) }
func (*PoInfo) ProtoMessage()    {}
func (*PoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{0, 0}
}

func (m *PoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoInfo.Unmarshal(m, b)
}
func (m *PoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoInfo.Marshal(b, m, deterministic)
}
func (m *PoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoInfo.Merge(m, src)
}
func (m *PoInfo) XXX_Size() int {
	return xxx_messageInfo_PoInfo.Size(m)
}
func (m *PoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PoInfo proto.InternalMessageInfo

func (m *PoInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PoInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PoInfo) GetHash() map[int64]*EntityItem {
	if m != nil {
		return m.Hash
	}
	return nil
}

type PoItems struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoItems) Reset()         { *m = PoItems{} }
func (m *PoItems) String() string { return proto.CompactTextString(m) }
func (*PoItems) ProtoMessage()    {}
func (*PoItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{0, 1}
}

func (m *PoItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoItems.Unmarshal(m, b)
}
func (m *PoItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoItems.Marshal(b, m, deterministic)
}
func (m *PoItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoItems.Merge(m, src)
}
func (m *PoItems) XXX_Size() int {
	return xxx_messageInfo_PoItems.Size(m)
}
func (m *PoItems) XXX_DiscardUnknown() {
	xxx_messageInfo_PoItems.DiscardUnknown(m)
}

var xxx_messageInfo_PoItems proto.InternalMessageInfo

type Entity struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{1}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

type EntityItem struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Slot                 []int32  `protobuf:"varint,2,rep,packed,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityItem) Reset()         { *m = EntityItem{} }
func (m *EntityItem) String() string { return proto.CompactTextString(m) }
func (*EntityItem) ProtoMessage()    {}
func (*EntityItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{1, 0}
}

func (m *EntityItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityItem.Unmarshal(m, b)
}
func (m *EntityItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityItem.Marshal(b, m, deterministic)
}
func (m *EntityItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityItem.Merge(m, src)
}
func (m *EntityItem) XXX_Size() int {
	return xxx_messageInfo_EntityItem.Size(m)
}
func (m *EntityItem) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityItem.DiscardUnknown(m)
}

var xxx_messageInfo_EntityItem proto.InternalMessageInfo

func (m *EntityItem) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *EntityItem) GetSlot() []int32 {
	if m != nil {
		return m.Slot
	}
	return nil
}

func init() {
	proto.RegisterEnum("pbRole.ModOpt", ModOpt_name, ModOpt_value)
	proto.RegisterType((*Po)(nil), "pbRole.po")
	proto.RegisterType((*PoInfo)(nil), "pbRole.po.info")
	proto.RegisterMapType((map[int64]*EntityItem)(nil), "pbRole.po.info.HashEntry")
	proto.RegisterType((*PoItems)(nil), "pbRole.po.items")
	proto.RegisterType((*Entity)(nil), "pbRole.entity")
	proto.RegisterType((*EntityItem)(nil), "pbRole.entity.item")
}

func init() { proto.RegisterFile("module.proto", fileDescriptor_ae7704718fb7daeb) }

var fileDescriptor_ae7704718fb7daeb = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0x45, 0x4d, 0xd3, 0x56, 0xfb, 0xc6, 0x45, 0x79, 0x6e, 0x6a, 0x41, 0x28, 0xb3, 0xaa, 0xa2,
	0x59, 0x8c, 0x20, 0xe2, 0x5e, 0x70, 0xa1, 0x08, 0xf9, 0x83, 0x0e, 0x8d, 0xb4, 0x4c, 0xdb, 0x17,
	0xa6, 0xa9, 0x90, 0x4f, 0xf2, 0x13, 0xfc, 0x3b, 0x49, 0x62, 0x5d, 0xb9, 0xbb, 0x5c, 0x2e, 0xe7,
	0x24, 0x0f, 0xce, 0x47, 0x6a, 0x97, 0x41, 0x09, 0x7d, 0x24, 0x43, 0x98, 0xea, 0xbd, 0xa4, 0x41,
	0x6d, 0xbf, 0x19, 0x44, 0x9a, 0xca, 0x2f, 0x06, 0x71, 0x3f, 0x7d, 0x10, 0xe6, 0xc0, 0x97, 0xbe,
	0x2d, 0x58, 0xc5, 0x6a, 0x2e, 0x5d, 0x44, 0x84, 0x78, 0x6a, 0x46, 0x55, 0x44, 0x15, 0xab, 0x33,
	0xe9, 0x33, 0xde, 0x41, 0xdc, 0x35, 0x73, 0x57, 0xf0, 0x8a, 0xd7, 0x9b, 0xdd, 0xa5, 0x08, 0x30,
	0xa1, 0x49, 0x38, 0x88, 0x78, 0x69, 0xe6, 0xee, 0x79, 0x32, 0x47, 0x2b, 0xfd, 0xac, 0x7c, 0x85,
	0xec, 0xaf, 0x72, 0x86, 0x83, 0xb2, 0xab, 0xe1, 0xa0, 0x2c, 0x5e, 0x43, 0xf2, 0xd9, 0x0c, 0x4b,
	0x50, 0x6c, 0x76, 0x17, 0x2b, 0x4e, 0x4d, 0xa6, 0x37, 0x56, 0xf4, 0x46, 0x8d, 0x32, 0x2c, 0x9e,
	0xa2, 0x47, 0x56, 0x9e, 0x42, 0xe2, 0xaa, 0x79, 0xfb, 0x00, 0x69, 0x98, 0x94, 0xb7, 0x10, 0xbb,
	0xea, 0xff, 0xd7, 0xcf, 0x03, 0x99, 0x22, 0xaa, 0x78, 0x9d, 0x48, 0x9f, 0x6f, 0xae, 0x20, 0x7d,
	0xa3, 0xf6, 0x5d, 0x1b, 0x3c, 0x0b, 0xbf, 0xce, 0x4f, 0x30, 0xfb, 0x85, 0xe6, 0x6c, 0x9f, 0xfa,
	0x0b, 0xdd, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xb9, 0x05, 0x73, 0x31, 0x01, 0x00, 0x00,
}
